name: Build and Push Docker Image

on:
  push:
    branches: [ "**" ]  # Trigger on any branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (insecure hardcoded)
        uses: docker/login-action@v3
        with:
          username: harishhari302        # <-- Replace this
          password: dckr_pat_TSc-6twWL9dMWaw5wHYRn-9vUVM    # <-- Replace this

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your_dockerhub_username/imharish-app:latest
